services:
  - type: web
    name: sihtemple-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: VITE_API_URL
        value: https://sihtemple2025t5.onrender.com/api
      - key: NODE_ENV
        value: production
